export const ChatThemes = {
  default: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.4",
    lineHeight: "@lineHeight",
    borderRadius: "@border-radius",
    borderWidth: "0",
    borderColor: "#dbdbdb",
    background: "#f5f5f5",
    color: "#0d0d0d",
    borderStyle: "solid",
    fontFamily: "@font-family",
    textareaBackground: "#ffffff",
    textareaColor: "#757a91",
    textareaRadius: 4,
    textareaBorderWidth: 1,
    textareaBorderColor: "#ced4da",
    bubbleShape: "speech",
    bubbleBorderRadius: 8,
    bubbleBorderWidth: "@border-width",
    bubblePadding: 10,
    bubbleIconSize: 12,
    bubbleIconColor: "#818181",
    assistantBackground: "@button-primary-background",
    assistantColor: "@button-primary-color",
    assistantBorderColor: "@button-primary-border-color",
    userBackground: "#ffffff",
    userColor: "#757a91",
    userBorderColor: "none",
    promptBackground: "#f0f0f0",
    promptColor: "#333",
    promptBorderColor: "#ccc",
    promptBorderWidth: 1,
    promptBorderRadius: 8,
    promptFontSize: 12,
    systempromptBackground: "#f0f0f0",
    systempromptColor: "#333",
    systempromptBorderColor: "#ccc",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 8,
    systempromptFontSize: 12,
    padding: 8,
    gap: 16,
    inputHeight: 50,
    bubbleIconColorHover: "#333",
    promptBackgroundHover: "#d1d1d1",
    promptColorHover: "#333",
    systempromptBackgroundHover: "#d1d1d1",
    systempromptColorHover: "#333",
    systempromptBorderColorHover: "#ccc",
    boxShadow: {
      v: 3,
      h: 3,
      b: 6,
      s: -2,
      c: "rgb(224, 224, 224)",
    },
    hover: {
      background: "#ffffff",
      color: "#757a91",
      borderColor: "#ced4da",
    },
  },
  purple: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.4",
    lineHeight: "@lineHeight",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ba68c8",
    background: "#fafafa",
    color: "#6a1b9a",
    borderStyle: "solid",
    textareaBackground: "#ffffff",
    textareaColor: "#8e24aa",
    textareaRadius: 4,
    textareaBorderWidth: 1,
    textareaBorderColor: "#eaeaea",
    bubbleShape: "speech",
    bubbleBorderRadius: 12,
    bubbleBorderWidth: 1,
    bubblePadding: 12,
    bubbleIconSize: 14,
    bubbleIconColor: "#ba68c8",
    assistantBackground: "#ffffff",
    assistantColor: "#4f4f4f",
    assistantBorderColor: "#f2f2f2",
    userBackground: "linear-gradient(45deg, #a056c8, #c05eed)",
    userColor: "#fcf5ff",
    userBorderColor: "#d0b0e2",
    promptBackground: "#a658cf",
    promptColor: "#fcf5ff",
    promptBorderColor: "#fdfcfe",
    promptBorderWidth: 1,
    promptBorderRadius: 12,
    promptFontSize: 12,
    systempromptBackground: "#f3e5f5",
    systempromptColor: "#6a1b9a",
    systempromptBorderColor: "#ba68c8",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 12,
    systempromptFontSize: 12,
    padding: 10,
    gap: 8,
    inputHeight: 52,
    bubbleIconColorHover: "#6a1b9a",
    promptBackgroundHover: "#9347ba",
    promptColorHover: "#fcf5ff",
    promptBorderColorHover: "#fdfcfe",
    systempromptBackgroundHover: "#d1c4e9",
    systempromptColorHover: "#6a1b9a",
    systempromptBorderColorHover: "#6a1b9a",
    boxShadow: {
      v: 3,
      h: 3,
      b: 6,
      s: -2,
      c: "rgb(224, 224, 224)",
    },
    hover: {
      background: "#ffffff",
      color: "#8e24aa",
      borderColor: "#eaeaea",
    },
  },
  blue: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.4",
    lineHeight: "@lineHeight",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#64b5f6",
    background: "#e3f2fd",
    color: "#0d47a1",
    borderStyle: "solid",
    textareaBackground: "#ffffff",
    textareaColor: "#01579b",
    textareaRadius: 4,
    textareaBorderWidth: 1,
    textareaBorderColor: "#64b5f6",
    bubbleShape: "speech",
    bubbleBorderRadius: 12,
    bubbleBorderWidth: 1,
    bubblePadding: 12,
    bubbleIconSize: 14,
    bubbleIconColor: "#4fc3f7",
    assistantBackground: "#e1f5fe",
    assistantColor: "#01579b",
    assistantBorderColor: "#64b5f6",
    userBackground: "#bbdefb",
    userColor: "#01579b",
    userBorderColor: "#64b5f6",
    promptBackground: "#e1f5fe",
    promptColor: "#01579b",
    promptBorderColor: "#64b5f6",
    promptBorderWidth: 1,
    promptBorderRadius: 12,
    promptFontSize: 13,
    systempromptBackground: "#e1f5fe",
    systempromptColor: "#01579b",
    systempromptBorderColor: "#64b5f6",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 12,
    systempromptFontSize: 13,
    padding: 10,
    gap: 16,
    inputHeight: 52,
    bubbleIconColorHover: "#01579b",
    promptBackgroundHover: "#cce4f7",
    promptColorHover: "#01579b",
    promptBorderColorHover: "#01579b",
    systempromptBackgroundHover: "#cce4f7",
    systempromptColorHover: "#01579b",
    systempromptBorderColorHover: "#01579b",
    boxShadow: {
      v: 3,
      h: 3,
      b: 6,
      s: -2,
      c: "rgb(224, 224, 224)",
    },
    hover: {
      background: "#ffffff",
      color: "#01579b",
      borderColor: "#64b5f6",
    },
  },
  dark: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.4",
    lineHeight: "@lineHeight",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#546e7a",
    background: "#37474f",
    color: "#eceff1",
    borderStyle: "solid",
    textareaBackground: "#263238",
    textareaColor: "#fffff",
    textareaRadius: 4,
    textareaBorderWidth: 1,
    textareaBorderColor: "#546e7a",
    bubbleShape: "speech",
    bubbleBorderRadius: 12,
    bubbleBorderWidth: 1,
    bubblePadding: 12,
    bubbleIconSize: 14,
    bubbleIconColor: "#b0bec5",
    assistantBackground: "#263238",
    assistantColor: "#cfd8dc",
    assistantBorderColor: "#546e7a",
    userBackground: "#37474f",
    userColor: "#cfd8dc",
    userBorderColor: "#546e7a",
    promptBackground: "#37474f",
    promptColor: "#cfd8dc",
    promptBorderColor: "#546e7a",
    promptBorderWidth: 1,
    promptBorderRadius: 12,
    promptFontSize: 13,
    systempromptBackground: "#37474f",
    systempromptColor: "#cfd8dc",
    systempromptBorderColor: "#546e7a",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 12,
    systempromptFontSize: 13,
    padding: 10,
    gap: 18,
    inputHeight: 52,
    bubbleIconColorHover: "#eceff1",
    promptBackgroundHover: "#546e7a",
    promptColorHover: "#eceff1",
    promptBorderColorHover: "#eceff1",
    systempromptBackgroundHover: "#546e7a",
    systempromptColorHover: "#eceff1",
    systempromptBorderColorHover: "#eceff1",
    boxShadow: {
      v: 2,
      h: 2,
      b: 5,
      s: 0,
      c: "rgba(0, 0, 0, 0.2)",
    },
    hover: {
      background: "#263238",
      color: "#cfd8dc",
      borderColor: "#546e7a",
    },
  },
  light: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.4",
    lineHeight: "@lineHeight",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cccccc",
    background: "#ffffff",
    color: "#333333",
    borderStyle: "solid",
    textareaBackground: "#ffffff",
    textareaColor: "#444",
    textareaRadius: 4,
    textareaBorderWidth: 1,
    textareaBorderColor: "#cccccc",
    bubbleShape: "speech",
    bubbleBorderRadius: 12,
    bubbleBorderWidth: 1,
    bubblePadding: 12,
    bubbleIconSize: 14,
    bubbleIconColor: "#999999",
    assistantBackground: "#f9f9f9",
    assistantColor: "#444",
    assistantBorderColor: "#dddddd",
    userBackground: "#ffffff",
    userColor: "#444",
    userBorderColor: "#cccccc",
    promptBackground: "#f9f9f9",
    promptColor: "#444",
    promptBorderColor: "#cccccc",
    promptBorderWidth: 1,
    promptBorderRadius: 12,
    promptFontSize: 13,
    systempromptBackground: "#f9f9f9",
    systempromptColor: "#444",
    systempromptBorderColor: "#cccccc",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 12,
    systempromptFontSize: 13,
    padding: 10,
    gap: 18,
    inputHeight: 52,
    bubbleIconColorHover: "#666666",
    promptBackgroundHover: "#e0e0e0",
    promptColorHover: "#333333",
    promptBorderColorHover: "#333333",
    systempromptBackgroundHover: "#e0e0e0",
    systempromptColorHover: "#333333",
    systempromptBorderColorHover: "#333333",
    boxShadow: {
      v: 3,
      h: 3,
      b: 6,
      s: -2,
      c: "rgb(224, 224, 224)",
    },
    hover: {
      background: "#ffffff",
      color: "#444",
      borderColor: "#cccccc",
    },
  },
  gradient: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.2",
    lineHeight: "@lineHeight",
    borderRadius: 12,
    borderWidth: 0,
    borderColor: "transparent",
    background: {
      colors: [
        {
          c: "#edf0f6",
          p: 2.5,
        },
        {
          c: "#a1ace8",
          p: 100,
        },
      ],
      gradient: true,
      direction: "45",
      gradientHeight: 300,
      gradientWidth: 30,
      selectedHandle: 0,
    },
    color: "#4a4a4a",
    borderStyle: "none",
    textareaBackground: "#f9f9f9",
    textareaColor: "#4a4a4a",
    textareaRadius: 16,
    textareaBorderWidth: 0,
    textareaBorderColor: "none",
    bubbleShape: "speech",
    bubbleBorderRadius: 12,
    bubbleBorderWidth: 0,
    bubblePadding: 16,
    bubbleIconSize: 16,
    bubbleIconColor: "#ffffff",
    assistantBackground: "linear-gradient(135deg, #f3f6ff, #ccd2e9)",
    assistantColor: "#322f4b",
    assistantBorderColor: "transparent",
    userBackground: "linear-gradient(135deg, #667eea, #6a5acd)",
    userColor: "#ffffff",
    userBorderColor: "transparent",
    promptBackground: "#979bf3",
    promptColor: "#ffffff",
    promptBorderColor: "transparent",
    promptBorderWidth: 0,
    promptBorderRadius: 12,
    promptFontSize: 12,
    systempromptBackground: "#d8def2",
    systempromptColor: "#494c89",
    systempromptBorderColor: "#c2c5ef",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 12,
    systempromptFontSize: 12,
    padding: 12,
    gap: 20,
    inputHeight: 56,
    bubbleIconColorHover: "transparent",
    promptBackgroundHover: "#7579ca",
    promptColorHover: "#ffffff",
    promptBorderColorHover: "transparent",
    systempromptBackgroundHover: "linear-gradient(135deg, #c2c5ef, #d8def2)",
    systempromptColorHover: "#494c89",
    systempromptBorderColorHover: "#c2c5ef",
    boxShadow: {
      v: 4,
      h: 4,
      b: 12,
      s: -3,
      c: "#9ea5ec",
    },
    hover: {
      background: "#ffffff",
      color: "#333333",
      borderColor: "#d1d5db",
    },
  },
  minimal: {
    fontSize: 14,
    textAlign: "left",
    letterSpacing: "0.8",
    lineHeight: "1.6",
    borderRadius: 16,
    borderWidth: 0,
    borderColor: "transparent",
    background: "#fff",
    color: "#333333",
    borderStyle: "none",
    textareaBackground: "rgb(244, 244, 244)",
    textareaColor: "rgb(13, 13, 13)",
    textareaRadius: 24,
    textareaBorderWidth: 0,
    bubbleShape: "none",
    bubbleBorderRadius: 24,
    bubbleBorderWidth: 0,
    bubblePadding: 16,
    bubbleIconSize: 16,
    bubbleIconColor: "#aeaeae",
    assistantBackground: "none",
    assistantColor: "rgb(13, 13, 13)",
    assistantBorderWidth: 1,
    assistantBorderColor: "#dbdbdb",
    userBackground: "#f3f3f3",
    userColor: "rgb(13, 13, 13)",
    userBorderColor: "rgb(227, 227, 227)",
    promptBackground: "rgb(244, 244, 244)",
    promptColor: "rgb(13, 13, 13)",
    promptBorderColor: "rgba(0, 0, 0, 0.1)",
    promptBorderWidth: 0,
    promptBorderRadius: 16,
    promptFontSize: 12,
    systempromptBackground: "#fdfdfd",
    systempromptColor: "rgb(13, 13, 13)",
    systempromptBorderColor: "rgba(0, 0, 0, 0.1)",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 24,
    systempromptFontSize: 14,
    padding: 14,
    gap: 8,
    inputHeight: 92,
    bubbleIconColorHover: "#ffffff",
    promptBackgroundHover: "rgb(249, 249, 249)",
    promptColorHover: "rgb(13, 13, 13)",
    promptBorderColorHover: "rgba(0, 0, 0, 0.1)",
    systempromptBackgroundHover: "rgb(249, 249, 249)",
    systempromptColorHover: "rgb(13, 13, 13)",
    systempromptBorderColorHover: "rgba(0, 0, 0, 0.1)",
    hover: {
      background: "#ffffff",
      color: "#333333",
      borderColor: "#d1d5db",
    },
    boxShadow: {
      v: 0,
      h: 0,
      b: 0,
      s: 0,
      c: "rgb(224, 224, 224)",
    },
  },
  solarized: {
    fontSize: 12,
    textAlign: "left",
    letterSpacing: "1.4",
    lineHeight: "@lineHeight",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#586e75",
    background: "#002b36",
    color: "#93a1a1",
    borderStyle: "solid",
    textareaBackground: "#002b36",
    textareaColor: "#839496",
    textareaRadius: 4,
    textareaBorderWidth: 1,
    textareaBorderColor: "#586e75",
    bubbleShape: "speech",
    bubbleBorderRadius: 12,
    bubbleBorderWidth: 1,
    bubblePadding: 12,
    bubbleIconSize: 14,
    bubbleIconColor: "#93a1a1",
    assistantBackground: "#002b36",
    assistantColor: "#839496",
    assistantBorderColor: "#586e75",
    userBackground: "#073642",
    userColor: "#839496",
    userBorderColor: "#586e75",
    promptBackground: "#073642",
    promptColor: "#839496",
    promptBorderColor: "#586e75",
    promptBorderWidth: 1,
    promptBorderRadius: 12,
    promptFontSize: 13,
    systempromptBackground: "#073642",
    systempromptColor: "#839496",
    systempromptBorderColor: "#586e75",
    systempromptBorderWidth: 1,
    systempromptBorderRadius: 12,
    systempromptFontSize: 13,
    padding: 10,
    gap: 18,
    inputHeight: 52,
    bubbleIconColorHover: "#93a1a1",
    promptBackgroundHover: "#586e75",
    promptColorHover: "#93a1a1",
    promptBorderColorHover: "#93a1a1",
    systempromptBackgroundHover: "#586e75",
    systempromptColorHover: "#93a1a1",
    systempromptBorderColorHover: "#93a1a1",
    boxShadow: {
      v: 3,
      h: 3,
      b: 6,
      s: -2,
      c: "#222222",
    },
    hover: {
      background: "#002b36",
      color: "#839496",
      borderColor: "#586e75",
    },
  },
};
