export default class HelperUtil {
    static SCREEN_MASTER = "https://help.flowrabbit.ai/en/category/master-screens/article/master-screen-basics"
    static SCREEN_SEGMENTS = "https://help.flowrabbit.ai/en/category/getting-started/article/screens"
    static SCREEN_TYPES = "https://help.flowrabbit.ai/en/category/getting-started/article/screens"
    static REST = "https://help.flowrabbit.ai/en/category/integrations/article/rest-api-integration"
    static SCRIPT = "https://help.flowrabbit.ai/en/category/getting-started/article/script"
    static DESIGN_TOKEN = "https://help.flowrabbit.ai/en/category/getting-started/article/design-token"
    static COMPONENTS = "https://help.flowrabbit.ai/en/category/getting-started/article/components"
    static DESIGN_IMPORT = "https://help.flowrabbit.ai/en/category/getting-started/article/design-import"
    static DESIGN_SYSTEM = "https://help.flowrabbit.ai/en/category/getting-started/article/design-system"
    static MASTER_SCREENS = "https://help.flowrabbit.ai/en/category/getting-started/article/master-screens"
    static FORM_VALIDATION = "https://help.flowrabbit.ai/en/category/getting-started/article/form-validation"
    static DATA_BINDING = "https://help.flowrabbit.ai/en/category/getting-started/article/data-binding"
    static LOGIC_FLOWS = "https://help.flowrabbit.ai/en/category/getting-started/article/logic-flows"
    static AB_TESTING = "https://help.flowrabbit.ai/en/category/getting-started/article/ab-testing"
    static ANIMATIONS = "https://help.flowrabbit.ai/en/category/getting-started/article/animations"
    static IMPORTS = "https://help.flowrabbit.ai/en/category/getting-started/article/imports"
    static OTHER = "https://help.flowrabbit.ai/en/category/getting-started/article/other"
    static TESTING = "https://help.flowrabbit.ai/en/category/getting-started/article/testing"
    static SURVEY = "https://help.flowrabbit.ai/en/category/getting-started/article/survey"
    static ANALYTIC_INTRO = "https://help.flowrabbit.ai/en/category/getting-started/article/analytic-intro"
    static ANALYTIC_TASKS = "https://help.flowrabbit.ai/en/category/getting-started/article/analytic-tasks"
    static ANALYTIC_SCATTER = "https://help.flowrabbit.ai/en/category/getting-started/article/analytics-scatter"
    static ANALYTIC_CANVAS = "https://help.flowrabbit.ai"
    static PROMPTS = "https://help.flowrabbit.ai/en/category/integrations/article/openai-chatgpt-integration"
    static CHAT = "https://help.flowrabbit.ai/en/category/integrations/article/openai-chatgpt-integration"
}